<div class="container" style="margin-top:70px;font-family:Courier;">
    <div class="row">	
		<div class="col-md-12">
			<div class="panel panels">
				<div class="panel-heading">
                    <div class="pageNotFound">
                        <h1>Oops! Error 404</h1>
                        <hr /><br >
                        <h3>Page Not Found</h3>
						<br ><br >
                    </div>					
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-md-12">
							<p>The requested page could not be found. Visit <a href="/">home</a> and to navigate through our menu</p>												
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>