<div class='home-banner-2'>
<section class="accordion-section clearfix mt-3" aria-label="Question Accordions">
  <div class="container" style="padding-top:80px;text-align:center;">
  
	  <h2>Frequently Asked Questions </h2><br />
	  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
		<div class="panel panel-default">
		  <div class="panel-heading p-3 mb-3" role="tab" id="heading0">
			<h3 class="panel-title">
			  <a class="collapsed" role="" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse0" aria-expanded="true" aria-controls="collapse0">
                WHAT IS Money In Crew?
			  </a>
			</h3>
		  </div>
		  <div id="collapse0" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading0">
			<div class="panel-body px-3 mb-4">
			  <p>Money In Crew is a Person to Person, Direct Funding and Crowd Sharing Platform. It brings forth a new way of raising funds for various causes, whether it is for personal needs or a host of worthy causes, such as churches, schools, non-profit organizations, etc.</p>			  
			</div>
		  </div>
		</div>
		
		<div class="panel panel-default">
		  <div class="panel-heading p-3 mb-3" role="tab" id="heading1">
			<h3 class="panel-title">
			  <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse1" aria-expanded="true" aria-controls="collapse1">
                IS Money In Crew A COMPANY, A BUSINESS OR A CORPORATION?
			  </a>
			</h3>
		  </div>
		  <div id="collapse1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading1">
			<div class="panel-body px-3 mb-4">
			  <p>Money In Crew is a Platform made by the people and for the people. It was created by a group of like-minded people for this very purpose.</p>
			</div>
		  </div>
		</div>
		
		<div class="panel panel-default">
		  <div class="panel-heading p-3 mb-3" role="tab" id="heading2">
			<h3 class="panel-title">
			  <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse2" aria-expanded="true" aria-controls="collapse2">
              HOW CAN I BE REFINED MEMBER?
			  </a>
			</h3>
		  </div>
		  <div id="collapse2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
			<div class="panel-body px-3 mb-4">
			  <p>
                To be a member of Money In Crew you must first join Through your sponsor or use our official site If you have been invited to join by a family member or friend/person, 
                click on that person’s “Refferal Link and you will be instructed to fill out a simplified registration form. In the event that you were not invited by family /friends then you can join by going to our official site Go to Sign-Up button. You will then be referred to someone in the Matrix and the system will automatically spill you down into the first eligible or qualified referrer’s group.
              </p>
			</div>
		  </div>
		</div>
		
		<div class="panel panel-default">
		  <div class="panel-heading p-3 mb-3" role="tab" id="heading3">
			<h3 class="panel-title">
			  <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse3" aria-expanded="true" aria-controls="collapse3">
              CAN I HAVE MORE THAN ONE ACCOUNT?
			  </a>
			</h3>
		  </div>
		  <div id="collapse3" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading3">
			<div class="panel-body px-3 mb-4">
			  <p>Yes you can as multiple accounts are allowed unlimitedly however it is important to know and stick to Money In Crew principle which is inviting 2 friends for each and every account u have.</p>
			</div>
		  </div>
		</div>

        <div class="panel panel-default">
		  <div class="panel-heading p-3 mb-3" role="tab" id="heading2">
			<h3 class="panel-title">
			  <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse4" aria-expanded="true" aria-controls="collapse4">
              CAN I SIGN PEOPLE UP MYSELF?
			  </a>
			</h3>
		  </div>
		  <div id="collapse4" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
			<div class="panel-body px-3 mb-4">
			    <p>
                Yes you can and it is advisable to do that to make sure that the people you refer are placed under the correct Referrer, which is you, but keep in mind that once you have 2 personal referrals, your additional referrals automatically spill down into your referrals genealogy. from the 1st generation level all the way down.
                </p>
			</div>
		  </div>
		</div>

        <div class="panel panel-default">
		  <div class="panel-heading p-3 mb-3" role="tab" id="heading2">
			<h3 class="panel-title">
			  <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse5" aria-expanded="true" aria-controls="collapse5">
              ARE THERE ANY FEES TO PAY?
			  </a>
			</h3>
		  </div>
		  <div id="collapse5" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
			<div class="panel-body px-3 mb-4">
			  <p>
              No, there are no fees of any kind. We offer the system 100% free of charge.</p>
			</div>
		  </div>
		</div>

        <div class="panel panel-default">
		  <div class="panel-heading p-3 mb-3" role="tab" id="heading2">
			<h3 class="panel-title">
			  <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse6" aria-expanded="true" aria-controls="collapse6">
              WHAT DONATION/PAY PROCESSORS ARE USED?
			  </a>
			</h3>
		  </div>
		  <div id="collapse6" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
			<div class="panel-body px-3 mb-4">
			  <p>
              Local Banks
              </p>
			</div>
		  </div>
		</div>

        <div class="panel panel-default">
		  <div class="panel-heading p-3 mb-3" role="tab" id="heading2">
			<h3 class="panel-title">
			  <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse7" aria-expanded="true" aria-controls="collapse7">
                ARE THE PAYMENTS AUTOMATED?
			  </a>
			</h3>
		  </div>
		  <div id="collapse7" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
			<div class="panel-body px-3 mb-4">
			  <p>
                No, as you receive donations from another participant, you will need to verify that the funds were deposited in whichever processor your Referral chose. Then and only then should you approve the donation. Donations must be approved within 12 hours. If the referrer does not take action within that time limit, their account will be blocked until some action is taken and during the locked timeframe, they will not be able to receive any donations; nor will they be able to donate.</p>
			</div>
		  </div>
		</div>

        <div class="panel panel-default">
		  <div class="panel-heading p-3 mb-3" role="tab" id="heading2">
			<h3 class="panel-title">
			  <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse8" aria-expanded="true" aria-controls="collapse8">
              CAN I EDIT MY PROFILE, E.G. CHANGE MY EMAIL ADDRESS OR DONATION METHODS?
			  </a>
			</h3>
		  </div>
		  <div id="collapse8" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
			<div class="panel-body px-3 mb-4">
			  <p>
              Yes, you are in control of your account. The only thing that cannot be edited is your username </p>
			</div>
		  </div>
		</div>

        <div class="panel panel-default">
		  <div class="panel-heading p-3 mb-3" role="tab" id="heading2">
			<h3 class="panel-title">
			  <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse9" aria-expanded="true" aria-controls="collapse9">
              CAN I CHANGE MY REFERRER?
			  </a>
			</h3>
		  </div>
		  <div id="collapse9" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
			<div class="panel-body px-3 mb-4">
			  <p>
                 No it's not possible to change referrer.
            </p>
			</div>
		  </div>
		</div>

        <div class="panel panel-default">
		  <div class="panel-heading p-3 mb-3" role="tab" id="heading2">
			<h3 class="panel-title">
			  <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse10" aria-expanded="true" aria-controls="collapse10">
                I SENT THE DONATION BUT MY REFERRER HAS NOT APPROVED IT. WHAT CAN I DO?
			  </a>
			</h3>
		  </div>
		  <div id="collapse10" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
			<div class="panel-body px-3 mb-4">
			  <p>
              Contact support submit valid proof of payments and support will acknowledge the payment on your behalf </p>
			</div>
		  </div>
		</div>

        <div class="panel panel-default">
		  <div class="panel-heading p-3 mb-3" role="tab" id="heading2">
			<h3 class="panel-title">
			  <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse11" aria-expanded="true" aria-controls="collapse11">
              ARE THERE ANY REFUNDS?
			  </a>
			</h3>
		  </div>
		  <div id="collapse11" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
			<div class="panel-body px-3 mb-4">
			  <p>
              No, there are no refunds, since all donations are sent directly from one person’s processor to another person’s processor. No funds are being held by the Administrator or the Founding group.  Money In Crew  has NO 3rd Party Processor to handle any transactions.
              </p>
			</div>
		  </div>
		</div>

        <div class="panel panel-default">
		  <div class="panel-heading p-3 mb-3" role="tab" id="heading2">
			<h3 class="panel-title">
			  <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse12" aria-expanded="true" aria-controls="collapse12">
              WHEN I WENT TO UPGRADE TO A HIGHER STAGE, THE SYSTEM SHOWS SOMEONE ELSE AS MY REFERRER ON THE UPGRADE TAB TO WHOM I HAVE TO SEND MY DONATION. WHY IS THAT?
			  </a>
			</h3>
		  </div>
		  <div id="collapse12" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
			<div class="panel-body px-3 mb-4">
			  <p>
              This is how a pass-up works. For example, your direct Referral donated R400 to you. When you step up or upgrade to Stage 2, the donation goes up to your Referrer's Referrer. When you step up to Stage 3, it goes to the 3rd Referrer, in that order all the way to Level 4 and that is how the donations from your generation’s referrals will flow up to you. Those that you see in your 1st generation are your direct referrals, which you have personally referred, and they will donate R400 to you. Those that you see in your 2nd generation will donate R500 to you when they step up to Stage 2. Those in all other stages will donate to you whenever they step up and submit the donation required for that particular Stage. As your donations increase with every Stage upgrade, the same applies to your referrals donations when they donate to you in the exact same fashion.</p>
			</div>
		  </div>
		</div>

        <div class="panel panel-default">
		  <div class="panel-heading p-3 mb-3" role="tab" id="heading2">
			<h3 class="panel-title">
			  <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse13" aria-expanded="true" aria-controls="collapse13">
              MY ACCOUNT IS BLOCKED WHAT SHOULD I DO ?
			  </a>
			</h3>
		  </div>
		  <div id="collapse13" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
			<div class="panel-body px-3 mb-4">
			<p>
                No need to worry login your dashboard and unblock your self
            </p>
			</div>
		  </div>
		  <br /><br />
		</div>
	  </div>
  
  </div>
</section>
</div>