
<div class="main-banner">
    <div class="main-banner-item banner-item-two">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div class="main-banner-content">
                        <h1>However, you make it we'll help you raise it</h1>
                        <p>Welcome to Wallet Booster a Peer2Peer donation platform which allows you to raise funds from your network of people.</p>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="main-banner-form">
                        <div class="content">
                            <h3>Sign into your account</h3>
                        </div>

                        <form action="/auth/authenticate" method="POST">
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="banner-form-btn">
                                        <a href="auth/" class="default-btn">
                                            Login
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<section class="services-area bg-ffffff pt-100 pb-70">
    <div class="container">
        <div class="section-title">
            <h2>Our platform is fully peer to peer and open.</h2>
        </div>

        <div class="owl-theme">
            <div class="single-services-item">
                <h3>
                    <a href="#">Testimonials</a>
                </h3>
                <p>We feature a fully functional testimonials system that allows people to post their successes in the platform with how much they donated to other people and how much they received from other people also.</p>
            </div>

            <div class="single-services-item">
                <h3>
                    <a href="#">Peer To Peer</a>
                </h3>
                <p>Being peer to peer our platform allows people to donate directly to our member's bank account ensuring transparent deployment of donations in a safe, secure and transparent manner.</p>
            </div>

            <div class="single-services-item">
                <h3>
                    <a href="#">Updates</a>
                </h3>
                <p>We believe keeping the platform up-to-date will improve overall usability and trustworthiness across the platform. We feature a comprehensive whatsapp based support line with on-platform news updates for any new features and news updates</p>
            </div>
        </div>
    </div>
</section>


<section class="overview-area ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="overview-content">
                    <h3>R 200 Start UP</h3>
                    <p>Donate R200 to your upliner and get downliners who will donate R200 each towards you and you can therefore upgrade to the next level with R400.</p>

                </div>
            </div>


            <div class="col-lg-12">
                <div class="overview-content">
                    <h3>Level 2 Donations</h3>
                    <p>Donate R400 towards your upliner's first upliner and your 4 level 2 downliners will each donate R400 towards you allowing you to upgrade to the final level with R800.<p></p>
                </div>
            </div>


            <div class="col-lg-12">
                <div class="overview-content">
                    <h3>Level 3 Donations</h3>
                    <p>Donate R800 to your upliner's second upliner and your 8 level 3 downliners will each donate R800 towards you allowing you to raise over R7200 using Wallet Booster.</p>

                </div>
            </div>
        </div>
    </div>
</section>