
<div class="copyright-area bg-color">
    <div class="container">
        <div class="copyright-area-content">
            <p>
                <i class='bx bx-copyright'></i>
                Copyright @ <?php echo Date('Y') .' - Wallet Booster';?>. All Rights Reserved
            </p>
        </div>
    </div>
</div>
<!-- End Copy Right Area -->

<!-- Start Go Top Area -->
<div class="go-top">
    <i class='bx bx-up-arrow-alt'></i>
</div>
<!-- End Go Top Area -->

<!-- Jquery Slim JS -->
<script src="/landing/js/jquery.min.js"></script>
<!-- Popper JS -->
<script src="/landing/js/popper.min.js"></script>
<!-- Bootstrap JS -->
<script src="/landing/js/bootstrap.min.js"></script>
<!-- Meanmenu JS -->
<script src="/landing/js/jquery.meanmenu.js"></script>
<!-- Nice Select JS -->
<script src="/landing/js/jquery.nice-select.min.js"></script>
<!-- Owl Carousel JS -->
<script src="/landing/js/owl.carousel.min.js"></script>
<!-- Magnific Popup JS -->
<script src="/landing/js/jquery.magnific-popup.min.js"></script>
<!-- Odometer JS -->
<script src="/landing/js/odometer.min.js"></script>
<!-- Jquery Appear JS -->
<script src="/landing/js/jquery.appear.min.js"></script>
<!-- Ajaxchimp JS -->
<script src="/landing/js/jquery.ajaxchimp.min.js"></script>
<!-- Form Validator JS -->
<script src="/landing/js/form-validator.min.js"></script>
<!-- Contact JS -->
<script src="/landing/js/contact-form-script.js"></script>
<!-- Wow JS -->
<script src="/landing/js/wow.min.js"></script>
<!-- Custom JS -->
<script src="/landing/js/main.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="/js/validateRegistration.js"></script>
<!--<script src="/js/passwordMeter.js"></script>-->
<script src="/js/dashboard3.js"></script>
<script src="/orgchart/jquery.min.js"></script>
<script src="/orgchart/jquery.orgchart.min.js"></script>
<script src="/js/tree.js"></script>
</body>
</html>