<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title><?php echo $this->getTitle();?></title>
    <link href="./backend/vendor/jqvmap/css/jqvmap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="./backend/vendor/chartist/css/chartist.min.css">
    <link href="./backend/vendor/bootstrap-select/dist/css/bootstrap-select.min.css" rel="stylesheet">
    <link href="./backend/css/style.css" rel="stylesheet">
    <link href="https://cdn.lineicons.com/2.0/LineIcons.css" rel="stylesheet">
    <script src="./backend/vendor/global/global.min.js"></script>
    <script src="./backend/vendor/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="./backend/vendor/chart.js/Chart.bundle.min.js"></script>
    <script src="./backend/js/custom.min.js"></script>
    <script src="./backend/js/deznav-init.js"></script>
    <script src="./vendor/waypoints/jquery.waypoints.min.js"></script>
    <script src="./vendor/jquery.counterup/jquery.counterup.min.js"></script>
    <script src="./vendor/apexchart/apexchart.js"></script>
    <script src="./vendor/peity/jquery.peity.min.js"></script>
    <script src="/js/dashboard3.js"></script>
    <script src="/js/validateRegistration5.js"></script>
</head>








<!doctype html>
<html lang="en">
    <head>

        <title>

        </title>

        <!--Character encoding, It lets you write text in all kinds of languages-->
        <meta charset="utf-8">

        <!--A <meta> viewport element gives the browser instructions on how to control the page's dimensions and scaling.
            The width=device-width part sets the width of the page to follow the screen-width of the device
            (which will vary depending on the device).
            The initial-scale=1.0 part sets the initial zoom level when the page is first loaded by the browser.
         -->
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!--Import my javascript functions
        <script src="/js/my_js_functions.js"></script>-->

        <!--Site Icon-->
        <link rel="icon" type="image/png" href="/images/logo4mobile.png">

        <script src='https://www.google.com/recaptcha/api.js' async defer></script>

        <!--Include bootstrap 4-->
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
        <script src="/js/dashboard3.js"></script>
        <script src="/js/validateRegistration5.js"></script>

        <!--Import my cascading stylesheet-->
        <link rel="stylesheet" href="/css/style.css" />

    </head>
    <body>
        