<!doctype html>
<html lang="zxx">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Peer2Peer Donation Platform" />
    <meta name="keywords" content="wallet-booster, donation, peer2peer" />
    <meta content="klass1k@protonmail.com" name="author" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/landing/css/bootstrap.min.css">
    <!-- Animate CSS -->
    <link rel="stylesheet" href="/landing/css/animate.min.css">
    <!-- Meanmenu CSS -->
    <link rel="stylesheet" href="/landing/css/meanmenu.css">
    <!-- Boxicons CSS -->
    <link rel="stylesheet" href="/landing/css/boxicons.min.css">
    <!-- Flaticon CSS -->
    <link rel="stylesheet" href="/landing/css/flaticon.css">
    <!-- Nice Select CSS -->
    <link rel="stylesheet" href="/landing/css/nice-select.min.css">
    <!-- Owl Carousel CSS -->
    <link rel="stylesheet" href="/landing/css/owl.carousel.min.css">
    <!-- Owl Carousel Default CSS -->
    <link rel="stylesheet" href="/landing/css/owl.theme.default.min.css">
    <!-- Odometer CSS -->
    <link rel="stylesheet" href="/landing/css/odometer.min.css">
    <!-- Magnific Popup CSS -->
    <link rel="stylesheet" href="/landing/css/magnific-popup.min.css">
    <!-- Style CSS -->
    <link rel="stylesheet" href="/landing/css/style.css">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="/landing/css/responsive.css">

    <title><?php echo $this->getTitle();?></title>

    <link rel="icon" type="image/png" href="/images/logo.jpg">
</head>

<body>

<!-- Start Preloader Area -->
<div class="preloader bg-4865ff">
    <div class="loader">
        <div class="shadow"></div>
        <div class="box"></div>
    </div>
</div>
<!-- End Preloader Area -->

<!-- Start Top Header Area -->
<div class="top-header-area bg-color">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <ul class="top-header-information">
                    <li>
                        <i class='bx bx-envelope'></i>
                        <a href="mailto:support@wallet-booster.com">support@wallet-booster.com</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- End Top Header Area -->

<!-- Start Navbar Area -->
<div class="navbar-area navbar-color-two">
    <div class="main-responsive-nav">
        <div class="container">
            <div class="main-responsive-menu">
                <div class="logo">
                    <a href="/">
                        <img src="#" alt="image" height="50">
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="main-navbar">
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-light">
                <a class="navbar-brand" href="/">
                    <img src="#" alt="image" height="50">
                </a>

                <div class="collapse navbar-collapse mean-menu" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="/" class="nav-link">
                                Home
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                About
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                Testimonials
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                FAQ's
                            </a>
                        </li>
                    </ul>

                    <div class="others-options d-flex align-items-center">
                        <div class="option-item">
                            <a href="/auth/" class="default-btn">Login</a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <div class="others-option-for-responsive color-two">
        <div class="container">
            <div class="dot-menu">
                <div class="inner">
                    <div class="circle circle-one"></div>
                    <div class="circle circle-two"></div>
                    <div class="circle circle-three"></div>
                </div>
            </div>

            <div class="container">
                <div class="option-inner">
                    <div class="others-options d-flex align-items-center">
                        <div class="option-item">
                            <a href="/auth/" class="default-btn">Login</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Navbar Area -->




          
        