<?php

    $_m = new memberClass();
    $_a = new allocationsClass();
    if(!isset($_POST['searchButton']))
        $_res = $_a->getAllAllocations();        
    else
        $_res = $_a->getSpecificAllocations($_POST['search']);
    

    $_a = new allocationsClass();
    $_t = new treeClass();
    $_i = new incentivesClass();
    $_b = new bankClass();
    $_d = new defaultsClass();

?>
<div class="container dash">	
	<div class="row">	
        <div class="col-md-3" id="navmenu">
            <div class="dleft">
                <div class="dleft_heading">Admin Menu</div>
                <ul>
                    <li><a href="/mystatsdir/admin">My Dashboard</a></li>
                    <hr />
                    <li><a href="/mystatsdir/admindefaults">Defaults</a></li>
                    <hr />
                    <li><a href="/mystatsdir/adminmembers">Members</a></li>
                    <hr />
                    <li><a href="/mystatsdir/adminpayments">Payments</a></li>
                    <hr />
                    <li><a href="/mystatsdir/adminevents">Upcoming events</a></li>
                    <hr />
                    <li><a href="/mystatsdir/adminnotifications">News updates</a></li>
                    <hr />
                    <li><a href="/mystatsdir/admintestimonials">Testimonials</a></li>
                </ul>
                <div class="dleft_heading"> </div>
                <ul>    
                    <li><a href="/auth/logout/"><h style="color:red; font-weight:600;">Sign Out</h></a></li>
                    <hr />      
                </ul>
            </div>    
        </div>
        <div class="col-md-9">
            <div class="dright">
                <div class="dright_heading">Events</div>
                <div class="body" style="overflow:auto;">
                    <div id="error_message">

                        <?php
				        	if(!empty($this->getMessage())){ //if($this->getMessage()<>''){ //if(!empty($this->getMessage())){
				        		echo '';
				        ?>
				        		<div class="alert <?php echo $this->getMessageType(); ?>" role="alert">									
  				        			<?php  echo $this->getMessage(); ?>
				        		</div>
				        <?php
				        	}	
				        ?>
                    </div>                                       
                    <!--Start payment-->  
                    
                    <!--End payment-->                                                                        
                </div>                                                         
            </div>            
        </div>
    </div>
</div>