<?php require_once(CORE.'recaptchalib.php'); ?>

<div style="background-image: url(/landing/skyline.jpg)">
    <div class="container">
        <div class="page-banner-content" >
            <h2>Login</h2>
            <ul>
                <li>
                    <a href="/">Home</a>
                </li>
                <li>Login</li>
            </ul>
        </div>
    </div>
</div>
<!-- End Page Banner -->

<!-- Start Open Account Banner -->
<section class="open-account-area ptb-100">
    <div class="container">
        <div class="section-title">
            <h2>WB Account</h2>
            <p>Login Into Your Account</p>
        </div>

        <div class="open-account-form">
            <form action="/auth/authenticate" method="post" autocomplete="off" novalidate>
                <?php
                if(!empty($this->getMessage())){ //if($this->getMessage()<>''){ //if(!empty($this->getMessage())){
                    echo '';
                    ?>
                    <div class="alert <?php echo $this->getMessageType(); ?>" role="alert">
                        <?php  echo $this->getMessage(); ?>
                    </div>
                    <?php
                }
                ?>
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <div class="form-group">
                            <label for="email">Username</label>
                            <input type="text" name="email"  id="Lusername" class="form-control" value="<?php
                            echo $this->getFailedEmail(); //echo !null($this->getFailedEmail()) ? $this->getFailedEmail() : '';
                            ?>" placeholder="Your Username">
                            <div id="error_lusername"></div>
                        </div>
                    </div>

                    <div class="col-lg-12 col-md-12">
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" name="password" id="Lpassword" class="form-control" placeholder="">
                            <div id="error_lpassword"></div>
                        </div>
                    </div>
                    <a href="/auth/fp/">Forgot Password?</a>
                    <div class="col-lg-12">
                        <div class="banner-form-btn">
                            <button type="submit" class="default-btn" name="login" id="login-submit">
                                Submit
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
